name = "text_unidecode"
uuid = "974fc1cd-5b3e-51bb-9c9c-9e2f6360840d"
authors = ["Alan Schelten <alan.schelten@mercateo.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
